-- AlterTable
ALTER TABLE "invoice_items" ADD COLUMN     "bag_weight_g" DECIMAL(10,3),
ADD COLUMN     "barcode" VARCHAR(80),
ADD COLUMN     "box_ref" VARCHAR(80),
ADD COLUMN     "box_weight_g" DECIMAL(10,3),
ADD COLUMN     "category" VARCHAR(80),
ADD COLUMN     "extra_amount" DECIMAL(14,2),
ADD COLUMN     "fine_amount" DECIMAL(14,2),
ADD COLUMN     "fine_weight_g" DECIMAL(10,3),
ADD COLUMN     "labor_amount" DECIMAL(14,2),
ADD COLUMN     "labor_on" VARCHAR(10),
ADD COLUMN     "labor_rate_with_tax" DECIMAL(10,4),
ADD COLUMN     "labor_rate_without_tax" DECIMAL(10,4),
ADD COLUMN     "less_weight_g" DECIMAL(10,3),
ADD COLUMN     "net_weight_g" DECIMAL(10,3),
ADD COLUMN     "packet_no" INTEGER,
ADD COLUMN     "pad_weight_g" DECIMAL(10,3),
ADD COLUMN     "plating" VARCHAR(80),
ADD COLUMN     "production_order_ref" VARCHAR(80),
ADD COLUMN     "purity" DECIMAL(6,3),
ADD COLUMN     "size" VARCHAR(40),
ADD COLUMN     "tag_weight_g" DECIMAL(10,3),
ADD COLUMN     "total_gross_weight_g" DECIMAL(10,3),
ADD COLUMN     "wastage_fine_g" DECIMAL(10,3),
ADD COLUMN     "wastage_percent" DECIMAL(6,3);
