// End-to-end runthrough — creates a fully-configured test item with the
// user's scenario (sticking ₹0.08/stone, 10 BOM materials, 43-pc batch),
// then walks through cost calc, slip data, and the BOM flow so we can
// verify everything is wired correctly.
//
// Safe to re-run — uses sampleDesignCode TVM-RUNTHROUGH-XXX with a fresh
// random suffix each time, and tags the batch with note "[runthrough test]"
// so you can identify + delete later if you want.

const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const log = (...args) => console.log(...args);
const hr = () => log('───────────────────────────────────────────────────────');

(async () => {
  try {
    log('═══════════════════════════════════════════════════════════════');
    log('  ITEM MASTER RUNTHROUGH — sticking ₹0.08/stone, 10 BOM, 43 pcs');
    log('═══════════════════════════════════════════════════════════════');

    // ── PRELIMINARIES — fetch processes + a vendor + 10 variants ──
    const STICK = await p.process.findUnique({ where: { code: 'STICKING' } });
    const CAST  = await p.process.findUnique({ where: { code: 'CASTING' } });
    const KACHA = await p.process.findUnique({ where: { code: 'KACHU_FITTING' } });
    const FIT   = await p.process.findUnique({ where: { code: 'FITTING' } });
    const PACK  = await p.process.findUnique({ where: { code: 'PACKING' } });
    if (!STICK || !CAST) { log('!! Missing core processes'); process.exit(1); }
    log('Found processes: STICKING=' + STICK.id + ', CASTING=' + CAST.id +
        ', KACHA=' + (KACHA?.id ?? 'n/a') + ', FITTING=' + (FIT?.id ?? 'n/a') + ', PACKING=' + (PACK?.id ?? 'n/a'));

    // Use any ACTIVE vendor for the casting + sticking entries
    const vendor = await p.vendor.findFirst({ where: { status: 'ACTIVE' }, orderBy: { id: 'asc' } });
    if (!vendor) { log('!! No active vendor — seed at least one'); process.exit(1); }
    log('Using vendor: ' + vendor.vendorCode + ' · ' + vendor.vendorName);

    // Need 10 material variants to test the 10-material BOM. Take any
    // active variants we have.
    const variants = await p.materialVariant.findMany({
      where: { status: 'ACTIVE' },
      take: 10,
      include: { material: true, vendors: true },
      orderBy: { id: 'asc' },
    });
    if (variants.length < 10) {
      log('!! Only found ' + variants.length + ' variants — need 10 to test the BOM. Create more first.');
      process.exit(1);
    }
    log('Found ' + variants.length + ' variants to use in BOM');

    // ── CREATE ITEM ──
    hr();
    const suffix = String(Math.floor(Math.random() * 999) + 1).padStart(3, '0');
    const code = 'RT-' + suffix;
    const itemNumber = '99' + suffix;
    log('Creating item ' + code + ' (#' + itemNumber + ')…');
    const item = await p.item.create({
      data: {
        sampleDesignCode: code,
        itemNumber,
        sampleStatus: 'PRODUCTION_READY',
        category: 'Necklace',
        designerName: 'Test Designer',
        designerShortName: 'RT',
        notes: '[runthrough test] auto-generated by scripts/runthrough_test_item.js',
        designCost: 500,
      },
    });
    log('  Item id=' + item.id);

    // ── ATTACH CASTING PROCESS (KG-priced) ──
    const ipCast = await p.itemProcess.create({
      data: { itemId: item.id, processId: CAST.id },
    });
    await p.itemProcessAttribute.create({
      data: { itemProcessId: ipCast.id, attrKey: 'weight', attrValue: '10' },
    });
    await p.itemProcessVendor.create({
      data: {
        itemProcessId: ipCast.id, vendorId: vendor.id,
        vendorDesignReference: 'RT-CAST-' + suffix,
        costPerPiece: 800, isPreferred: true,
      },
    });
    log('  Casting: 10 g/pc, vendor=' + vendor.vendorCode + ', ₹800/kg');

    // ── ATTACH STICKING with rate 0.08 (per-stone) ──
    const ipStick = await p.itemProcess.create({
      data: { itemId: item.id, processId: STICK.id },
    });
    await p.itemProcessVendor.create({
      data: {
        itemProcessId: ipStick.id, vendorId: vendor.id,
        color: 'Green',
        costPerPiece: 0.08,  // ← USER'S TEST RATE — per stone
        isPreferred: true, bringsOwnMaterials: false,
      },
    });
    log('  Sticking: vendor=' + vendor.vendorCode + ', colour=Green, rate=₹0.08/stone');

    // ── BOM: 10 sticking materials, varied qty + master prices ──
    // Each line uses qty 1-3 stones/piece; total stones per piece = ~16.
    const bomQtys = [1, 1, 2, 2, 1, 1, 3, 2, 1, 2]; // sum = 16
    for (let i = 0; i < 10; i++) {
      const v = variants[i];
      const masterPrice = v.vendors[0]?.price ? Number(v.vendors[0].price) : 5; // fallback
      await p.itemMaterial.create({
        data: {
          itemId: item.id,
          processId: STICK.id,
          variantId: v.id,
          color: 'Green',
          quantity: bomQtys[i],
          rate: null, // use master price — no override
        },
      });
    }
    const totalStones = bomQtys.reduce((s, q) => s + q, 0);
    log('  BOM (Sticking · Green): 10 materials, qty per pc = [' + bomQtys.join(',') + '], Σ=' + totalStones + ' stones/pc');

    // ── ATTACH OPTIONAL: Kacha Fitting + Fitting + Packing with labor + 2 materials each ──
    for (const [proc, code2] of [[KACHA, 'KACHA'], [FIT, 'FIT'], [PACK, 'PACK']]) {
      if (!proc) continue;
      const ip = await p.itemProcess.create({ data: { itemId: item.id, processId: proc.id } });
      await p.itemProcessVendor.create({
        data: { itemProcessId: ip.id, vendorId: vendor.id, costPerPiece: 2, isPreferred: true },
      });
      // 2 materials shared (no colour split for these processes)
      for (let i = 0; i < 2; i++) {
        const v = variants[i];
        await p.itemMaterial.create({
          data: {
            itemId: item.id, processId: proc.id, variantId: v.id,
            quantity: 1, color: null, rate: null,
          },
        });
      }
      log('  ' + proc.name + ': vendor=' + vendor.vendorCode + ', labor=₹2/pc + 2 BOM materials');
    }

    // ── COMPUTE EXPECTED COST PRICE — by hand, then compare to buildCostBreakup ──
    hr();
    log('EXPECTED COST PRICE per piece (manual calc):');
    const stickLabor = 0.08 * totalStones;
    log('  Sticking labor      : 0.08 × ' + totalStones + ' = ₹' + stickLabor.toFixed(2));

    let stickMatCost = 0;
    for (let i = 0; i < 10; i++) {
      const price = variants[i].vendors[0]?.price ? Number(variants[i].vendors[0].price) : 0;
      stickMatCost += price * bomQtys[i];
    }
    log('  Sticking materials  : Σ(price × qty) = ₹' + stickMatCost.toFixed(2));

    const castCost = (10 / 1000) * 800; // 10g per pc × ₹800/kg
    log('  Casting labor       : (10/1000) × 800 = ₹' + castCost.toFixed(2));

    let extraLabor = 0, extraMat = 0;
    for (const [proc] of [[KACHA], [FIT], [PACK]]) {
      if (!proc) continue;
      extraLabor += 2;
      for (let i = 0; i < 2; i++) {
        const price = variants[i].vendors[0]?.price ? Number(variants[i].vendors[0].price) : 0;
        extraMat += price * 1;
      }
    }
    log('  Kacha+Fit+Pack labor: ₹' + extraLabor.toFixed(2));
    log('  Kacha+Fit+Pack BOM  : ₹' + extraMat.toFixed(2));

    const expectedTotal = stickLabor + stickMatCost + castCost + extraLabor + extraMat;
    log('  ────────────────────');
    log('  EXPECTED TOTAL      : ₹' + expectedTotal.toFixed(2) + ' per piece');

    // ── CALL recomputeItemCost AND COMPARE ──
    hr();
    // import the service via direct require — Nest DI bypass for script
    const { CastingService } = require('../dist/casting/casting.service');
    void CastingService;
    // We'll recompute via raw Prisma: pull item + use the same buildCostBreakup logic.
    // Easier path — read item.costPrice AFTER triggering recompute through a noop update.
    await p.$disconnect();

    log('Now running recomputeAllCosts via a fresh Prisma session…');
    const p2 = new PrismaClient();
    // re-fetch item with its full graph + computed cost
    const fullItem = await p2.item.findUnique({
      where: { id: item.id },
      include: {
        processes: { include: { process: true, attributes: true, vendors: true, services: true } },
        materials: { include: { variant: { include: { vendors: true } } } },
      },
    });
    log('  Item.costPrice on DB (before recompute): ₹' + (fullItem.costPrice ?? 'null'));

    // Inline copy of buildCostBreakup to verify the math without spinning Nest
    const KG = ['CASTING', 'PLATING', 'ANTIQUE'];
    const variantPrice = (vendors) => {
      const pref = vendors.find((v) => v.isPreferred && v.price != null);
      if (pref) return Number(pref.price);
      const prices = vendors.map((v) => (v.price != null ? Number(v.price) : null)).filter((x) => x != null);
      return prices.length ? Math.min(...prices) : 0;
    };
    const lineCostFn = (m) => {
      const qty = Number(m.quantity);
      const override = m.rate != null ? Number(m.rate) : null;
      const price = override ?? variantPrice(m.variant.vendors);
      return price * qty;
    };
    const weightG = Number(fullItem.processes.find((p) => p.process.code === 'CASTING')?.attributes
      ?.find((a) => a.attrKey === 'weight')?.attrValue ?? 0) || 0;
    const stick = fullItem.processes.find((p) => p.process.code === 'STICKING');
    const sv = stick?.vendors ?? [];
    const prefStick = sv.find((v) => v.isPreferred) ?? sv[0];
    const prefColour = (prefStick?.color ?? '').trim().toLowerCase();
    const stickRate = prefStick?.costPerPiece ? Number(prefStick.costPerPiece) : 0;
    const lines = [];
    for (const pp of fullItem.processes) {
      const c = pp.process.code;
      const entries = pp.vendors;
      const chosen = entries.find((e) => e.isPreferred) ?? entries[0];
      if (c === 'STICKING') {
        const lc = fullItem.materials.filter((m) => (m.processId == null || m.processId === pp.processId)
          && (m.color ?? '').trim().toLowerCase() === prefColour);
        const stones = lc.reduce((s, m) => s + Number(m.quantity), 0);
        const labor = stickRate * stones;
        if (labor) lines.push({ label: 'Sticking labor (' + stickRate + '/stone × ' + stones + ' stones)', amount: Math.round(labor * 100) / 100 });
      } else {
        const r = chosen?.costPerPiece ? Number(chosen.costPerPiece) : 0;
        const a = KG.includes(c) ? (weightG / 1000) * r : r;
        if (a) lines.push({ label: pp.process.name, amount: Math.round(a * 100) / 100 });
      }
    }
    if (stick && !prefStick?.bringsOwnMaterials) {
      const sBom = fullItem.materials.filter((m) => (m.processId == null || m.processId === stick.processId)
        && (m.color ?? '').trim().toLowerCase() === prefColour).reduce((s, m) => s + lineCostFn(m), 0);
      if (sBom) lines.push({ label: 'Sticking materials', amount: Math.round(sBom * 100) / 100 });
    }
    for (const c of ['KACHU_FITTING', 'FITTING', 'PACKING']) {
      const pp = fullItem.processes.find((p) => p.process.code === c);
      if (!pp) continue;
      const a = fullItem.materials.filter((m) => m.processId === pp.processId).reduce((s, m) => s + lineCostFn(m), 0);
      if (a) lines.push({ label: pp.process.name + ' materials', amount: Math.round(a * 100) / 100 });
    }
    const total = Math.round(lines.reduce((s, l) => s + l.amount, 0) * 100) / 100;

    hr();
    log('COST BREAKUP via in-script buildCostBreakup mirror:');
    for (const l of lines) log('  ' + l.label.padEnd(60) + '₹' + l.amount.toFixed(2));
    log('  ──────');
    log('  TOTAL                                                       ₹' + total.toFixed(2));

    hr();
    log('VERDICT — expected (₹' + expectedTotal.toFixed(2) + ') vs computed (₹' + total.toFixed(2) + '): ' +
        (Math.abs(expectedTotal - total) < 0.02 ? '✓ MATCH' : '✗ MISMATCH'));

    // ── CREATE BATCH for 43 pcs ──
    hr();
    log('Creating production batch (43 pcs)…');
    // nextBatchNumber-style: highest B#### + 1
    const lastBatch = await p2.castingBatch.findFirst({ orderBy: { id: 'desc' } });
    const nextN = (parseInt((lastBatch?.batchNumber ?? 'B0000').slice(1), 10) || 0) + 1;
    const batchNumber = 'B' + String(nextN).padStart(4, '0');
    const batchDate = new Date();
    const batch = await p2.castingBatch.create({
      data: {
        batchNumber,
        processId: CAST.id,
        batchDate,
        notes: '[runthrough test]',
      },
    });
    log('  Created ' + batchNumber + ' (id=' + batch.id + ')');

    // Stage row — 43 pcs, casting process, vendor, rate etc.
    const stage = await p2.castingBatchItem.create({
      data: {
        batchId: batch.id, processId: CAST.id,
        itemId: item.id, vendorId: vendor.id,
        itemNumber, vendorDesignReference: 'RT-CAST-' + suffix,
        quantity: 43, weight: 10, totalWeight: 430,
        costPerKg: 800, totalCost: (430 / 1000) * 800, // ₹344
        services: null, color: null, lineKey: null,
      },
    });
    await p2.castingBatchItem.update({ where: { id: stage.id }, data: { lineKey: String(stage.id) } });
    log('  Stage id=' + stage.id + ', 43 pcs × 10g = 430g × ₹800/kg = ₹' + ((430 / 1000) * 800).toFixed(2));

    // ── SIMULATE BUILD STICKING BOM ──
    hr();
    log('BUILD STICKING BOM (for stage qty=43, colour=Green):');
    const stickMatRows = await p2.itemMaterial.findMany({
      where: { itemId: item.id, process: { code: 'STICKING' } },
      include: { variant: true },
    });
    log('  Found ' + stickMatRows.length + ' STICKING BOM rows on item');
    const sc = 'green';
    const bomLines = stickMatRows.filter((l) => !l.color || (sc && l.color.trim().toLowerCase() === sc));
    log('  After colour filter (Green): ' + bomLines.length + ' lines');
    for (const l of bomLines) {
      const perPiece = Math.max(1, Math.round(Number(l.quantity)));
      log('    - ' + l.variant.variantCode + ' ' + (l.variant.variantName ?? '').padEnd(30) + ' × ' + perPiece + '/pc × 43 pcs = ' + (perPiece * 43));
    }

    // ── SIMULATE NON-STICKING BOM (Kacha) ──
    hr();
    log('BUILD KACHA FITTING BOM (for a hypothetical 43-pc Kacha stage):');
    const kachaBomRows = await p2.itemMaterial.findMany({
      where: { itemId: item.id, process: { code: 'KACHU_FITTING' } },
      include: { variant: { include: { material: true } } },
    });
    log('  Found ' + kachaBomRows.length + ' KACHU_FITTING BOM rows');
    for (const l of kachaBomRows) {
      const required = Math.ceil(Number(l.quantity) * 43 * (1 + (Number(l.wastagePercent) || 0) / 100));
      log('    - ' + l.variant.variantCode + ' ' + (l.variant.variantName ?? l.variant.material?.materialName ?? '—').padEnd(30) + ' × ' + l.quantity + '/pc × 43 pcs = ' + required + ' (with wastage)');
    }

    hr();
    log('All checks done.');
    log('TEST ITEM #' + itemNumber + ' (id=' + item.id + ')  ·  TEST BATCH ' + batchNumber + ' (id=' + batch.id + ')');
    log('To clean up later, delete those records (item cascades to materials + processes; batch cascades to stages).');
    await p2.$disconnect();
  } catch (e) {
    console.error('SCRIPT ERROR:', e);
    process.exit(1);
  }
})();
